name: Agente v3

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install playwright
          playwright install --with-deps

      - name: Verificar pacotes instalados
        run: pip list

      - name: Rodar scraper
        run: python scraper.py

      - run: pip install requests

      - name: Rodar notifier
        run: python notifier.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
